version: "3.7"
services:
  web:
    container_name: anonymousdiary
    restart: unless-stopped
    volumes:
      - data:/code/diaries
    build: .
    environment:
      - PYTHONUNBUFFERED=1
volumes:
  data:
#networks:
#  default:
#    external:
#      name: nginxnet
