version: "3.7"
services:
  web:
    container_name: anonymousdiary
    restart: unless-stopped
    volumes:
      - diaries:/code/diaries
    build: .
    ports:
      - "5001:5001"
    environment:
      - PYTHONUNBUFFERED=1
volumes:
  diaries:
#networks:
#  default:
#    external:
#      name: nginxnet
